Repository netlify/delta-action, pull requests merged in 2021-05, with the labels that each got.

#45 chore: run CI on latest Node.js
  .github/workflows/prepare.yml
  .github/workflows/workflow.yml
Labels: type: chore

#54 feat: add graph for historical data
  src/lib/comment.js
  src/lib/graph.js
Labels: type: feature

#58 fix: improve graph rendering
  src/lib/graph.js
Labels: type: bug

#64 fix: reduce max graph items
  src/lib/comment.js
Labels: type: bug

#66 fix: show most recent items in graph
  src/lib/comment.js
Labels: type: bug
